language: node_js
before_install:
- npm install -g grunt-cli
script:
- grunt
before_deploy:
- grunt package
deploy:
  provider: releases
  api_key:
    secure: ltH+RsNd/SeytQ9KA8NWI6t1lAJzk+QRc5VQL4WjVd9SS0Hwv4Z7bK8hV0B9xzHDGDr2PMElSFd2rNhQ+UtjVYgkfsJe2+JKA7mI5uqjdXpL7K/FZZcRNH483p/ZiUFf9fGG65JrFOIYwbHJqUEkYRyzDeGUf0fgBkNlwjG+/wHHlGBYK2LRtFrLGYseABCaVKIoxWvHHH6cxlQ3F7z7FFA5HwEMArmsIQ+7GR/GnUM+n9ULFfviq4VXzmBJgIDZLbkA9P37Qzwjp6DWsfjEOUBS1ryqSeJwDWOkdbSFeFi/rcOcx65N94VotlRPK34Z/gFliJkfoYWQL3uLMs7cjM8ii7n8s1UWv9K46cTdPC4S6iYZ+I1E7KPaupLZuOTXf89lvjZUomSNWqV7K2JiKYEUq6pN9csTfUkELICy3PJgvLgdLqGhNitrRSIjTMUQW/HbOLyXHdaQ9utZJKo8AwjIcL8M2KMsdeC04wdiXWPrphjSDImzNDMYI5dNQ62+1MDKOE5G09bMTRrvlYTfHIOWWd0f+ei7/nUA3z+lPAcbpSa15LmQ+3xyIsCUUQqoJYLj3xOhZpXpaUv8VmEXMpparM+RhH4xZvXhiTr8t0zV3xopOxj0C3Ef1Kgars8P+TY8yQ3jiDSK/Pz+qUtnPcK8UhPPm3g84xliAU87SJ0=
  skip_cleanup: true
  file_glob: true
  file: gallerizejs-*
  on:
    tags: true
